  0%|                                                           | 0/80 [00:19<?, ?it/s]
0 25113 1.5071805715560913
1 25113 0.9902448058128357
2 25113 1.1431448459625244
Traceback (most recent call last):
  File "/code/RLoc/training/train.py", line 31, in <module>
    do_train(params, debug=args.debug, device=device)
  File "/code/RLoc/training/trainer.py", line 372, in do_train
    for index, (query, positives, negatives) in enumerate(dataloaders[phase]):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/code/RLoc/training/dataset.py", line 991, in __getitem__
    neg = np.array(Image.open(neg_image_path)).astype(np.float32)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 701, in __array_interface__
    new["data"] = self.tobytes()
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 758, in tobytes
    self.load()
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageFile.py", line 269, in load
    n, err_code = decoder.decode(b)
KeyboardInterrupt
