  0%|                                                                               | 0/120 [01:00<?, ?it/s]
0 44266 1.1542125940322876
1 44266 0.4847152829170227
2 44266 1.7351819276809692
3 44266 0.6269382238388062
4 44266 1.6863081455230713
5 44266 1.5262457132339478
6 44266 0.844021201133728
7 44266 1.2730202674865723
8 44266 0.7560137510299683
9 44266 0.5896889567375183
10 44266 0.5181498527526855
11 44266 0.41148537397384644
12 44266 0.7273128628730774
13 44266 0.5436596274375916
14 44266 0.7763811945915222
15 44266 1.1424680948257446
16 44266 1.0199031829833984
17 44266 0.839210569858551
Traceback (most recent call last):
  File "/code/RLoc/training/train.py", line 31, in <module>
    do_train(params, debug=args.debug, device=device)
  File "/code/RLoc/training/trainer.py", line 358, in do_train
    for index, (query, positives, negatives) in enumerate(dataloaders[phase]):
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/code/RLoc/training/dataset.py", line 131, in __getitem__
    pos = np.array(Image.open(pos_image_path)).astype(np.float32)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3268, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 3254, in _open_core
    im = factory(fp, filename)
  File "/usr/local/lib/python3.9/site-packages/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/usr/local/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 750, in _open
    s = self.png.call(cid, pos, length)
  File "/usr/local/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 205, in call
    return getattr(self, "chunk_" + cid.decode("ascii"))(pos, length)
  File "/usr/local/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 430, in chunk_IHDR
    s = ImageFile._safe_read(self.fp, length)
KeyboardInterrupt
